[package]
name = "hlbsp"
version = "0.4.6"
authors = ["r4v3n6101 <raven6107@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.20"
glium = "0.28.0"
render = { path = "render" }
cgmath = "0.17.0"

[dependencies.log]
version = "0.4.11"
features = ["std", "max_level_debug", "release_max_level_info"]

[workspace]
members = ["file", "render"]

[profile.release]
opt-level = 'z'
lto = true
panic = "abort"
codegen-units = 1
