[package]
name = "hlbsp"
version = "0.1.2"
authors = ["r4v3n6101 <raven6107@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "*"
glium = "*"
cgmath = "*"
bsp = { path = "bsp" }
wad = { path = "wad" }
itertools = "*"
nom = "*"
log = { version = "*", features = ["std", "max_level_debug", "release_max_level_info"] }
elapsed = "*"

[workspace]
members = ["bsp", "wad"]
