[package]
name = "hlbsp"
version = "0.4.6"
authors = ["r4v3n6101 <raven6107@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "*"
glium = "*"
render = { path = "render" }
cgmath = "*"

[dependencies.log]
version = "*"
features = ["std", "max_level_debug", "release_max_level_info"]

[workspace]
members = ["file", "render"]

[profile.release]
opt-level = 'z'
lto = true
panic = "abort"
codegen-units = 1
