[package]
name = "file"
version = "0.3.0"
authors = ["r4v3n6101 <raven6107@gmail.com>"]
edition = "2018"

[dependencies]
arraylib = "*"

[dependencies.nom]
version = "*"
default-features = false
features = ["std"]

[dependencies.image]
version = "*"
default-features = false
features = ["tga"]
