[package]
name = "render"
version = "0.3.11"
authors = ["r4v3n6101 <raven6107@gmail.com>"]
edition = "2018"

[dependencies]
file = { path = "../file/" }
nom = "5.1.2"
glium = "*"
cgmath = "*"
itertools = "*"
elapsed = "*"
log = "*"
