[package]
name = "render"
version = "0.1.0"
authors = ["r4v3n6101 <raven6107@gmail.com>"]
edition = "2018"

[dependencies]
nom = "*"
glium = "*"
cgmath = "*"
bsp = { path = "../bsp/" }

[dev-dependencies]
wad = { path = "../wad/" }
