[package]
name = "render"
version = "0.3.2"
authors = ["r4v3n6101 <raven6107@gmail.com>"]
edition = "2018"

[dependencies]
file = { path = "../file/" }
nom = "*"
glium = "*"
itertools = "*"
log = "*"
