[package]
name = "render"
version = "0.4.0"
authors = ["r4v3n6101 <raven6107@gmail.com>"]
edition = "2018"

[dependencies]
file = { path = "../file/" }
glium = "0.29.0"
cgmath = "0.17.0"
itertools = "0.9.0"
elapsed = "0.1.2"
log = "0.4.11"
